server:
  port: 19010
  # 종료 신호를 받으면 기존 요청이 완료될 시간을 주고, 새로운 요청은 받지 않도록 하는 방식
  shutdown: graceful

spring:
  application:
    name: user-service

  lifecycle:
    # Graceful Shutdown 단계별 최대 대기 시간
    timeout-per-shutdown-phase: 30s

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      # Flyway가 스키마를 관리하므로 Hibernate는 엔티티-스키마 일치 여부만 검증
      ddl-auto: validate
    open-in-view: false

  flyway:
    # users 테이블 명세서 기준 스키마
    schemas: user_service

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

jwt:
  # Access Token 설정 정보
  secret: ${JWT_SECRET}
  access-token-expiry-seconds: 1800 #만료시간 30분

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    # Eureka Server에 주소를 등록할 때 hostname 대신 IP를 선호
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}

  client:
    # Eureka Server에 User Service 등록
    register-with-eureka: true

    # Eureka Registry의 서비스 목록을 가져옴
    fetch-registry: true

    service-url:
      # Eureka Server 주소
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:19000/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus

  tracing:
    sampling:
      # 로컬에서는 모든 요청을 trace 대상으로 잡음
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

springdoc:
  paths-to-exclude: /api/*/internal/**