-- event_outbox의 발행 순서를 확정하기 위한 단조 증가 시퀀스 컬럼.
--
-- 기존에는 created_at으로 정렬했으나, PostgreSQL의 CURRENT_TIMESTAMP는
-- 트랜잭션 시작 시각으로 고정되므로 같은 sync() 트랜잭션에서 적재된
-- HEALTH_ACTIVITY_SYNCED와 QUEST_SUGGESTED가 동일한 created_at을 갖는다.
-- 정렬 키가 동점이면 SQL은 행 순서를 보장하지 않아 발행 순서가 역전될 수 있고,
-- 그 결과 Game Service가 이전 누적값으로 Quest baseline을 고정하게 된다.
--
-- outbox_id는 UUID.randomUUID()라 삽입 순서를 반영하지 않으므로
-- 타이브레이커로 쓸 수 없어 별도의 시퀀스 컬럼을 둔다.
ALTER TABLE health_service.event_outbox
    ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 폴링 쿼리(status = ? ORDER BY seq)가 인덱스를 그대로 타도록 정렬 키를 교체한다.
DROP INDEX IF EXISTS health_service.idx_health_activity_outbox_status;

CREATE INDEX idx_health_activity_outbox_status
    ON health_service.event_outbox (status, seq);