apiVersion: 1

policies:
  - orgId: 1

    # Grafana Alert를 Slack Contact Point로 전달
    receiver: slack-monitoring-alert

    # 같은 알림과 서비스를 하나의 그룹으로 묶음
    group_by:
      - alertname
      - job

    # 최초 알림 전송 전 대기 시간
    group_wait: 10s

    # 같은 그룹의 추가 알림 전송 간격
    group_interval: 5m

    # 미해결 상태가 지속될 경우 재알림 간격
    repeat_interval: 4h